services:
  - type: web
    name: ai-genesis-engine
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python run_server_prod.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false  # Add this in Render dashboard
      - key: FRONTEND_URL
        value: https://*.lovable.app 