services:
  - type: web
    name: ai-genesis-engine
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn src.genesis_engine.web_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: ANTHROPIC_API_KEY
        sync: false  # Add this in Render dashboard
      - key: FRONTEND_URL
        value: https://*.lovable.app 