
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables directly
const supabaseUrl = 'https://gpebuaywtxdjvwpspwyz.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZWJ1YXl3dHhkanZ3cHNwd3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODcxMzIsImV4cCI6MjA2NTQ2MzEzMn0.4ahgxM_sGcAL_dnmazDiRVqNPhp59_8wMA3-0D2SLuc';
const appVersion = import.meta.env.VITE_APP_VERSION || '1.0.0';

// Supabase client configuration options
const supabaseOptions = {
  auth: {
    persistSession: true,
    storageKey: 'ai-genesis-engine-auth',
    detectSessionInUrl: true,
  },
  db: {
    schema: 'public' as const,
  },
  global: {
    headers: {
      'X-Client-Info': `ai-genesis-engine@${appVersion}`,
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  supabaseUrl,
  supabaseAnonKey,
  supabaseOptions
);
