// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpebuaywtxdjvwpspwyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZWJ1YXl3dHhkanZ3cHNwd3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODcxMzIsImV4cCI6MjA2NTQ2MzEzMn0.4ahgxM_sGcAL_dnmazDiRVqNPhp59_8wMA3-0D2SLuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);